# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1c\n\x0cTextResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"!\n\nAudioChunk\x12\x13\n\x0b\x61udio_bytes\x18\x01 \x01(\x0c\x32\xdd\x01\n\x10InferenceService\x12\x44\n\x10TranscribeStream\x12\x15.inference.AudioChunk\x1a\x17.inference.TextResponse(\x01\x12=\n\nFormatText\x12\x16.inference.TextRequest\x1a\x17.inference.TextResponse\x12\x44\n\x10TranscribeAndFix\x12\x15.inference.AudioChunk\x1a\x17.inference.TextResponse(\x01\x42/Z!murmur/go-server/gen/go/inference\xaa\x02\tInferenceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z!murmur/go-server/gen/go/inference\252\002\tInference'
  _globals['_TEXTREQUEST']._serialized_start=30
  _globals['_TEXTREQUEST']._serialized_end=57
  _globals['_TEXTRESPONSE']._serialized_start=59
  _globals['_TEXTRESPONSE']._serialized_end=87
  _globals['_AUDIOCHUNK']._serialized_start=89
  _globals['_AUDIOCHUNK']._serialized_end=122
  _globals['_INFERENCESERVICE']._serialized_start=125
  _globals['_INFERENCESERVICE']._serialized_end=346
# @@protoc_insertion_point(module_scope)
